name: sumo
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - pip
  - numpy=1.23
  - pytorch=1.12.1
  - cudatoolkit=11.3
  - cython<3
  - faiss-gpu
  - glfw
  - six
  - pip:
      - git+https://github.com/Farama-Foundation/d4rl@master
      - mujoco-py==2.1.2.14
      - tensorboard
      - scikit-learn
